/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** ProblemDetails */
    ProblemDetails: {
      /**
       * Format: uri
       * @description Identifica o tipo do problema: `about:blank` para falhas HTTP genéricas ou `{APP_URL}/problems/{slug}` para falhas da aplicação. Compare apenas o slug.
       * @example about:blank
       */
      type: string
      /**
       * @description Resumo do problema para exibir ao usuário. Não use para decidir comportamento.
       * @example Não encontrado
       */
      title: string
      /**
       * @description Código de status HTTP, igual ao da resposta.
       * @example 404
       */
      status: number
      /** @description Explicação desta ocorrência para exibir ao usuário. */
      detail?: string
      /**
       * @description Código de rastreio da requisição (também no header `X-Trace-Id`). Informe-o ao suporte.
       * @example 4bf92f3577b34da6a3ce929d0e0e4736
       */
      trace_id: string
    }
    /** ValidationProblemDetails */
    ValidationProblemDetails: {
      /**
       * Format: uri
       * @description Identifica o tipo do problema: `about:blank` para falhas HTTP genéricas ou `{APP_URL}/problems/{slug}` para falhas da aplicação. Compare apenas o slug.
       * @example about:blank
       */
      type: string
      /**
       * @description Resumo do problema para exibir ao usuário. Não use para decidir comportamento.
       * @example Dados inválidos
       */
      title: string
      /**
       * @description Código de status HTTP, igual ao da resposta.
       * @example 422
       */
      status: number
      /** @description Explicação desta ocorrência para exibir ao usuário. */
      detail?: string
      /**
       * @description Código de rastreio da requisição (também no header `X-Trace-Id`). Informe-o ao suporte.
       * @example 4bf92f3577b34da6a3ce929d0e0e4736
       */
      trace_id: string
      /** @description Mensagens de validação, agrupadas pelo nome do campo. */
      errors: {
        [key: string]: string[]
      }
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
